# Site
url: "https://aiagentmanifesto.org"
favicon: 'favicon.png'

plugins: 
  - jekyll-sitemap
  - jekyll-redirect-from

# Syntax
markdown: kramdown

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.md, CONTRIBUTING.md]
